### ISSUE TITLE
 Supervise the grasp pose of "tasks"

### ISSUE THREAD

**Issue by lif314** [xukechun/Vision-Language-Grasping#6]
How to supervise the grasping of "tasks"? For example, if I want "the cup", my task is to "pour" (task) water, so the part I want to grasp should be the cup handle, not other parts of the cup. I'm very confused about this point!

**Comment by xukechun** [comment]
Hi,

This problem is also interesting, namely task-oriented grasping (TOG), where the robot should reason the grasping part of the object for the following task. Our work lies in the concept of target-oriented grasping, which aims to successfully grasp the object specified by the language, and does not consider the following task. Now there are some datasets for task-oriented grasp, e.g. TaskGrasp, GraspGPT. Also, LLM is a good tool to generate the grasping part of the same object according to different tasks.
Hope this helps you.

Best,
Kechun Xu
